import "./globals.css";
import Navbar from '../components/Navbar/NavbarWrapper'
import Footer from '../components/UI/Footer'
import { auth } from "@/lib/auth/auth";
import { headers } from "next/headers";

export const metadata = {
  title: "Gatherly",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default async function RootLayout({ children }) {

  const session = await auth.api.getSession({
    headers: await headers(),
  });
  return (
    <html lang="en">
      <body className="antialiased bg-linear-to-t from-[#fbc2eb] to-[#a6c1ee] min-h-screen flex flex-col">
        <Navbar session={session} />
        <main className="grow p-4 pb-24 bg-transparent">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
