import "./globals.css";
import Navbar from '../components/Navbar/NavbarWrapper'
import Footer from '../components/UI/Footer'

export const metadata = {
  title: "Gatherly",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-gradient-to-t from-[#fbc2eb] to-[#a6c1ee] min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-grow p-4 pb-24 bg-transparent">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
