import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../components/NavbarWrapper'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="bg-gradient-to-t from-[#fbc2eb] to-[#a6c1ee] min-h-screen">
        {children}  
      </div>
        
      </body>
    </html>
  );
}
